plugins { id 'com.android.application' }

android {
    namespace 'com.lordofthenorth'
    compileSdk 35

    defaultConfig {
        applicationId 'com.lordofthenorth'
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        resources { excludes += ['/META-INF/{AL2.0,LGPL2.1}'] }
    }

    aaptOptions { noCompress 'wav' }
}
